jp/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", v.register, name="register"),
    path("", include("jp_app.urls")),
    path("", include("to_do_list.urls")),
    path('', include("django.contrib.auth.urls")),
]

to_do_list/urls.py
from django.urls import path

from . import views
#from .views import IdeaView

app_name = 'to_do_list'


urlpatterns = [
    path("to_do_list/", views.to_do_list, name="to_do_list"),
    path("to_to_list-update/<int:id>",
         views.to_to_list_update, name="to_to_list_update"),
]

to_do_list/models.py
from django.db import models
import datetime
from datetime import date
# importuje textové pole s možností editace textu (velikost písma, barva atd.)
from ckeditor.fields import RichTextField

# Create your models here.

class ToDoList(models.Model):
    name = models.CharField(max_length=256)  ### název úkolu
    content = RichTextField(blank=True, null=True)  ### poznámka
    checked = models.BooleanField()
    date = models.DateField(blank=True, null=True)  # termín úkolu
    created = models.DateTimeField(auto_now_add=True) ### automaticky doplní čas přidání úkolu

to_do_list/forms.py
from django import forms
from .models import ToDoList
from django.forms import ModelForm
# importuje textové pole s možností editace textu (velikost písma, barva atd.)
from ckeditor.fields import RichTextField

import datetime
from datetime import date


class DateInput(forms.DateInput):
    input_type = 'date'
    
    
class ToDoListForm(ModelForm):
    class Meta:
        model = ToDoList
        fields = ["name", "content", "checked", "date"]
        labels = {
            'name': ('Úkol'),
            'content': ('Obsah'),
            'checked': ('Hotovo'),
            'date': ('Datum vložení'),
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-sm', 'placeholder': 'Název položky', 'title': 'Your name'}),
            'content': RichTextField(),
            #'checked': forms.Select(attrs={'class': 'form-control form-control-sm'}),
            'date': DateInput()}

to_do_list/views.py
### imports

from django.shortcuts import render
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.contrib import messages

from .models import ToDoList

from .forms import ToDoListForm


### views

def to_do_list(response):
    t = ToDoList.objects.all()
    
    if response.method == "POST":
        print("POST")
        if "add" in response.POST:
            name = response.POST.get('name')
            print("name: ", name)
            date = response.POST.get('date')
            print("date: ", date)
            content = response.POST.get('content')
            checked = response.POST.get('checked')
            print("checked: ", checked)
            if checked == "on":
                checked = True
            else:
                checked = False
            print("checked: ", checked)
            new_t = ToDoList(
                name=name,
                date=date,
                #date=None,
                content=content,
                #checked=True,
                checked=checked,
                )
            new_t.save()
        
        elif "delete_t" in response.POST:
            ### uloží "id" položky, kterou chceme smazat
            x = response.POST['delete_t']
            ### vyhledá odpovídající položku (dle id=x)
            z = ToDoList.objects.get(id=x)
            z.delete()  # vymaže danou položku
            messages.success(response, ('Úkol byl úspěšně vymazán'))
    
    dict = {
        "t": t,
    }
    return render(response, "to_do_list/to_do_list.html", dict)


def to_to_list_update(response, id):
    item = ToDoList.objects.get(id=id)
    form = ToDoListForm(response.POST or None,
                    instance=item)
    if form.is_valid():
        form.save()
        messages.success(response, ('Úkol byl úspěšně změněn'))
        return redirect("/to_do_list")

    dict = {
        "form": form,
        "item": item,
    }

    return render(response, "to_do_list/to_to_list-update.html", dict)

to_do_list/templates/to_do_list/to_do_list.html
<!DOCTYPE html>
<html>
<style>
    span.small {
  font-size: smaller;
}
    table,
    th,
    td {
        border: 1px solid black;
    }
</style>

<body>

{% extends 'jp_app/base.html' %}

{% block title %}
ToDoList
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<span class="small">

<br>
<div class="p-3 mb-2 bg-info text-white">To Do List</div>

{% comment %} Formulář pro přidání položky ToDoListu {% endcomment %}
<div class="card border-info mb-3">
<div class="card-body">
<form method="post" action="/to_do_list/" class="row">
  {% csrf_token %}

  <div class="col-sm-6">
    <label class="visually-hidden" for="autoSizingInputGroup">Name</label>
    <div class="input-group mb-3">
      <div class="input-group-text">Úkol</div>
      <input type="text" class="form-control" name="name" placeholder="Název úkolu" id="autoSizingInputGroup">
    </div>
    
    <label class="visually-hidden" for="datepicker">Date</label>
    <div class="input-group mb-3 date" id="datepicker">
        <input type="text" class="form-control" name="date" placeholder="Vyberte datum - termín úkolu">
        <span class="input-group-append">
            <span class="input-group-text bg-white d-block">
                <i class="fa fa-calendar"></i>
            </span>
        </span>
    </div>

    <script type="text/javascript">
        $(function() {
            $('#datepicker').datepicker(
                {
                    orientation: "bottom",
                    weekStart: 0,
                    rtl: true,
                    language: 'cs-CZ',
                    format: 'yyyy-mm-dd',
                    
                  
                }
            );
        });
    </script>
  </div>
  <div class="col-sm-6">
    <label class="visually-hidden" for="autoSizingInputGroup2">Content</label>
    <div class="input-group">
        <div class="input-group-text">Obsah</div>
        <textarea class="form-control" name="content" placeholder="Obsah úkolu (nepovinné)" id="autoSizingInputGroup2" style="height: 90px"></textarea>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="form-check">
        <input class="form-check-input" name="checked" type="checkbox" id="gridCheck">
        <label class="form-check-label" for="gridCheck">
        Hotovo
        </label>
    </div>
  </div>
  <div class="col-sm-6">
    <button type="submit" name="add" class="btn btn-info btn-rounded">Uložit</button>
  </div>
</form>
</div>
</div>

{% comment %} Seznam položek ToDoList {% endcomment %}
<hr>

<form method="post" action="#">
{% csrf_token %}
<div class="table-responsive">
<table class="table table-striped table-sm">
    <thead class="table-info">
        <tr>
            <th scope="col">Hotovo</th>
            <th scope="col">Název</th>
            <th scope="col">Obsah</th>
            <th scope="col">Termín</th>
            <th scope="col">Vytvořeno</th>
            <th scope="col">Editace</th>
            <th scope="col">Smazat</th>
        </tr>
    </thead>
    <tbody>
        
        {% for item in t %}
            <tr>
               
                <td>{% if item.checked %}Ano{% endif %}{% if not item.checked %}{% endif %}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.content|safe }}</td>
                <td>{{ item.date }}</td>
                <td>{{ item.created|date:'d.m.Y H:i:s' }}</td>
                <td><a href="{% url 'to_do_list:to_to_list_update' item.id %}" class="btn btn-info btn-sm">Editovat</a></td>
                <td><button type="submit" , name="delete_t" , value="{{item.id}}" , class="btn btn-danger btn-sm">Smazat</button></td>
            </tr>
  
        {% endfor %}
    </tbody>
</table>
</div>
</form>

</body>

</span>

{% endblock %}

to_do_list/templates/to_do_list/to_to_list-update.html
{% extends 'jp_app/base.html' %}

{% block title %}ToDoList{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<br>
<div class="p-3 mb-2 bg-info text-white">ToDoList</div>

<hr>
<h2>Editace ToDoList</h2>
<div class="form-row align-items-center">
    <div class="col-auto">
        <form method="POST">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button class="btn btn-success">Upravit</button>
        </form>
    </div>
</div>


{% endblock %}