jp/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", v.register, name="register"),
    path("", include("jp_app.urls")),
    path("", include("to_do_list.urls")),
    path('', include("django.contrib.auth.urls")),
]

jp_app/urls.py
from django.urls import path

from . import views
from .views import IdeaView, IdeaDetailView, CreateIdea, UpdateIdea, DeleteIdea
from .views import ProductView, ProductDetailView, CreateProduct, UpdateProduct, DeleteProduct


app_name = 'jp_app'

urlpatterns = [
    path("", views.home, name="home"),
    path("<int:id>", views.index, name="index"),
    
    path("list", views.list, name="list"),
    path("create/", views.create, name="create"),
    
    path("product/", ProductView.as_view(), name="product"),
    path("product/<int:pk>", ProductDetailView.as_view(), name="product-detail"),
    path("product_update/<int:pk>", UpdateProduct.as_view(), name="product_update"),
    path("product_delete/<int:pk>", DeleteProduct.as_view(), name="product_delete"),
    path("product_add/", CreateProduct.as_view(), name="product_add"),
    
    path("item/", views.item, name="item"),
    path("item_update/<int:id>", views.item_update, name="item_update"),

    path("material/", views.material, name="material"),
    path("list_material/", views.list_material, name="list_material"),
    
    path("material_chart/", views.material_chart, name="material_chart"),
    path("statistic/", views.statistic, name="statistic"),
    path("stat_chart/", views.stat_chart, name="stat_chart"),
    
    path("google/", views.google, name="google"),
    
    path("render_pdf/",
         views.render_pdf, name="render_pdf"),
    
    path("idea/", IdeaView.as_view(), name="idea"),
    path("idea/<int:pk>", IdeaDetailView.as_view(), name="idea-detail"),
    path("idea_update/<int:pk>", UpdateIdea.as_view(), name="idea_update"),
    path("idea_delete/<int:pk>", DeleteIdea.as_view(), name="idea_delete"),
    path("idea_add/", CreateIdea.as_view(), name="idea_add"),
    
    # path('jp_candles/', include("jp_candles_app.urls"))
]

jp_app/views.py
from django import forms
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, FileResponse
from django.db.models import Sum, Count
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from collections import Counter

from .models import ProductType, Product, Item, SaleType, Sale, Transaction
from .models import MaterialType, Material, Storage, Removal
from .models import Idea

from .forms import ProductTypeForm, ProductForm, ItemForm, SaleTypeForm, SaleForm, TransactionForm, SearchForm
from .forms import MaterialTypeForm, MaterialForm, StorageForm, RemovalForm
from .forms import IdeaForm

from .filters import TransactionFilter

from .utils import (
    get_sales_channel_from_id,
    get_product_from_id, 
    get_chart_price,
    get_json,
)
    
import datetime
import pandas as pd
import json

### google drive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
import os

### pdf creator
import csv
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

from django.template.loader import render_to_string
from io import BytesIO
from xhtml2pdf import pisa


###   PRODEJ   ###



### zobrazí seznam všech produktů, i když zadám konkrétní "id"
def index(response, id):
    p = Product.objects.get(id=id)
    return render(response, "jp_app/list.html", {})

### zobrazí domovskou stránku (aktuálně bez obsahu)
def home(response):
    return render(response, "jp_app/home.html", {})


class ProductView(ListView):
    model = Product
    template_name = 'jp_app/product/product.html'
    ordering = ['-created']  # seřadí seznam produktů sestupně dle "data vložení"
    paginate_by = 15 ### pokud bude mít seznam více než  15 položek, rozdělí se v teplate na více stránek
    
    ### fce "get_context_data" umožňuje upravovat a přidávat pole/hodnoty v následně zobrazené template u class Views (v tomto případě ListView)
    ### v tomto případě fce spočítá celkové výrobní náklady z jednotlivých položek "items" obsažených/přiřazených danému produktu
    def get_context_data(self, **kwargs):
        ### "context" předdefinovaný (neměnit)
        context = super(ProductView, self).get_context_data(**kwargs)
        ### prochází postupně všechny produkty
        for p in Product.objects.all(): 
            i_sum=0
            ### prochází a postupně ukládá ceny ("costs") všech "items" obsažených v daném produktu
            for i in p.items.values('costs'):
                i_sum += i['costs']
            ### uloží do pole "production_costs" daného produktu celkovou částku za všechny "items" a tím vypočítá výrobní náklady daného produktu
            p.production_costs = i_sum
            p.save()
        ### "context" umožní zobrazení nově upraveného pole "production_costs" v template 'jp_app/product/product.html'
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'jp_app/product/product-detail.html'


### automaticky (pomocí CreateView) načte formulář sloužící k vložení produktů
class CreateProduct(SuccessMessageMixin, CreateView):
    ### "SuccessMessageMixin" slouží k tomu, aby se po vložení produktu a přesměrování na seznam produktů (k tomu slouží atribut "success_url") mohlo zobrazit potvrzení uložení
    model = Product  # models.py
    form_class = ProductForm  # forms.py
    # pokud kvůli bootstrap mám "template_name", musím zakomentovat "fields"
    template_name = 'jp_app/product/product_add.html'
    # template_name = 'jp_app/idea_add.html'
    # fields = '__all__'
    success_url = reverse_lazy('jp_app:product') ### po uložení produktu přesměruje na stránku se seznamem produktů
    success_message = "Produkt %(name)s byl úspěšně uložen" ### po vložení zobrazí upozornění
    

class UpdateProduct(UpdateView):
    model = Product
    form_class = ProductForm  # forms.py
    # pokud kvůli bootstrap mám "template_name", musím zakomentovat "fields"
    template_name = 'jp_app/product/product_update.html'
    # fields = '__all__'


class DeleteProduct(DeleteView):
    model = Product
    template_name = 'jp_app/product/product_delete.html'
    # 'reverse_lazy' slouží k určení stránky, na kterou po smazání nápadu bude přesměrováno
    success_url = reverse_lazy('jp_app:product')


### vytvoří a zobrazí seznam "items", tzn. jednotlivých položek, ze kterých se skládají produkty
def item(response):
    i = Item.objects.all()
    i_count = i.count()  ### fce počítá součet vložené typy produktů
    form_i = ItemForm()
    
    if response.method == "POST":
        if "save_i" in response.POST: 
            form_i = ItemForm(response.POST)
            if form_i.is_valid():
                form_i.save()
        if response.POST.get("delete_i"):
            # převede QueryDict na dictionary "id" položky, kterou chceme smazat
            x = response.POST.dict()['delete_i']
            # vyhledá odpovídající transakci (dle id=x)
            z = Item.objects.get(id=x)
            z.delete()  # vymaže danou položku naskladnění
            messages.success(response, ('Item byla úspěšně vymazán'))
    
    
    dict = {
        "i": i,
        "i_count": i_count,
        "form_i": form_i,
      }

    return render(response, "jp_app/product/item.html", dict)


### umožní editovat objekt "item"
def item_update(response, id):
    item = Item.objects.get(id=id)
    form = ItemForm(response.POST or None,
                    instance=item)
    if form.is_valid():
        form.save()
        messages.success(response, ('Item byla úspěšně změněna'))
        return redirect("/item")
    
    dict = {
        "form": form,
        "item": item,
    }
    
    return render(response, "jp_app/product/item_update.html", dict)



### zobrazí všechny položky kategorie prodej ###
def list(response):
    pt = ProductType.objects.all()
    p = Product.objects.all()
    st = SaleType.objects.all()
    s = Sale.objects.all()
    t = Transaction.objects.all()

    ### slouží k vymazání dané transakce ###
    if response.method == "POST":
        ### aktivace tlačítkem "delete" u příslušné transakce
        if response.POST.get("delete_t"):
            # převede QueryDict na dictionary "id" položky, kterou chceme smazat
            x = response.POST.dict()['delete_t']
            # vyhledá odpovídající transakci (dle id=x)
            z = Transaction.objects.get(id=x)
            z.delete()  # vymaže danou položku naskladnění
            messages.success(response, ('Transakce byla úspěšně vymazána'))
    
    ### další část kód slouží k výpočtu tržeb po jednotlivých dnech ###
    q = Transaction.objects.values('day_of_sale').distinct() ### uloží unikátní dny, ve kterých se uskutečnila transakce (class Transaction)
    #print(q)
    tt = []
    temp1 = 0
    total = 0
    for date in q: ### prochází postupně všechny dny, kdy se uskutečnila transakce
        t1 = Transaction.objects.filter(day_of_sale=date["day_of_sale"]) ### uloží konkrétní den dané iterace cyklu "for"
        #print(t1)
        #print(len(t1))
        temp = 0
        lst = []
        for x in range(len(t1)): ### prochází postupně všechny transakce daného dne
            #print(x)
            temp += (t1[x]).total_price  ### uloží utrženou částku za danou transakci
            
        ### We can use (*) operator to get all the values of the dictionary in a list
        temp_value = [*(q[temp1]).values()][0] ### uloží hodnotu data aktuální iterace (* a fce values slouží k očištění daného data, aby nebylo zabaleno v listu a dalo se dále uložit)
        lst.extend([temp_value, temp])  # přidá do dočasného listu datum z temp_value spolu s utrženou částkou v daném dni (fce"extend" je alternativou k "append" a slouží k vložení více hodnot do listu najdednou)
        #print(lst)
        tt.append(lst) ### vloží hodnoty z dočasného listu "lst" do finálního souhrnného listu "tt", který obsahuje všechny potřebného hodnoty pro výpis tržeb
        total += temp ### počítá celkovou utrženou částku za všechny transakce
        temp1 += 1
    #print(tt)


    ### vypočte, kolik bylo prodáno ks jednotlivých výrobků (z uskutečněných transakcí) ###
    id_p = Product.objects.values('id')
    ### prochází jednotlivé výrobky dle "id"
    for product in id_p:
        # print("id_p:", id_p)
        # print("product['id']:", product['id'])
        ### z trasakcí seskupených dle "id" prodaného výrobku vypočte celkový počet prodaných ks daného výrobku
        y = Transaction.objects.filter(product__id=product['id']).values(
            'product').annotate(sum=Sum('quantity_of_product')).values('sum')
        ### "z1" je list_comprehension, jehož výsledkem je ale list, proto se zatám nepoužívá a místo toho je níže "for z in y", které z QuerySetu vyndá počet prodaných výrobků pro další použití
        # z1 = ([z['sum'] for z in y])
        # print("z1:",z1)
        for z in y:
            ### najde produkt, který je aktuálně součástí daného cyklu "for product in id_p"
            pr1 = Product.objects.get(id=product['id'])
            ### k danému atributu "sold" daného produktu přiřadí počet prodaných ks a uloží ho
            pr1.sold = z['sum']
            pr1.save()

    print(t.values('day_of_sale'))
    
    ### tato část slouží k filtrování transakcí ###
    myFilter = TransactionFilter(response.GET, queryset=t) 
    t = myFilter.qs
    #print(t)

    ### fce počítá součet vložené typy produktů ###
    pt_count = pt.count()


    
    dict = {
        "pt": pt,
        "p": p,
        "st": st,
        "s": s,
        "t": t,
        "q": q,
        "myFilter": myFilter,
        "pt_count": pt_count,
        "tt": tt,  ### obsahuje všechny potřebného hodnoty pro výpis tržeb
        "total": total,  ### celková utržená částka za všechny transakce
         }

jp_app/templates/jp_app/product/item.html
<!DOCTYPE html>
<html>
<style>
    span.small {
  font-size: smaller;
}
    table,
    th,
    td {
        border: 1px solid black;
    }
</style>

<body>

{% extends 'jp_app/base.html' %}

{% block title %}Item{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<br>

<span class="small">

<div class="p-3 mb-2 bg-dark text-white">ITEMS</div>

<hr>

<div class="col">
    <div class="card text-white bg-success">
        <div class="card-body">
            <h5 class="card-title">Tvorba item</h5>
            <p class="card-text">
                <form method="post" action="/item/" class="form-group">
                    {% csrf_token %}
                    {{ form_i.as_table }}
                    <button type="submit" , name="save_i" , value="i" , class="btn btn-dark">Vložit</button>
                </form>
            </p>
        </div>
    </div> 
</div>

<hr>

<div class="p-2 mb-2 bg-info text-black"><strong>Seznam items</strong></div>
<p>Celkový počet položek: {{ i_count }}</p>
<form method="post" action="#">
<div class="table-responsive">
{% csrf_token %}
<table class="table table-striped table-sm" id="myTable1">
    <thead class="table-info">
        <tr>
            <th scope="col">Název</th>
            <th scope="col">Cena</th>
            <th scope="col">Dodavatel</th>
            <th scope="col">Odkaz</th>
            <th scope="col">Poznámka</th>
            <th scope="col">Přidáno</th>
            <th scope="col">Editace</th>
            <th scope="col">Smazání</th>
        </tr>
    </thead>
    <tbody>
        {% for item in i %}
            <tr>
                <th scope="row">{{ item.name }}</th>
                <td>{{ item.costs }} Kč</td>
                <td>{{ item.supplier }}</td>
                <td>{% if item.link %}<a href="{{ item.link }}">{{ item.link }}</a>{% endif %}</td>
                <td>{{ item.note }}</td>
                <td>{{ item.created|safe }}</td>
                <td><a href="{% url 'jp_app:item_update' item.id %}" class="btn btn-info btn-sm">Editovat</a></td>
                <td><button type="submit" , name="delete_i" , value="{{item.id}}" , class="btn btn-danger btn-sm">Smazat</button></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</form>

</span>

{% endblock %}

jp_app/templates/jp_app/product/item_update.html
{% extends 'jp_app/base.html' %}

{% block title %}Item{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<br>
<div class="p-3 mb-2 bg-info text-white">ITEMS</div>

<hr>
<h2>Editace item</h2>
<div class="form-row align-items-center">
    <div class="col-auto">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success">Upravit</button>
        </form>
    </div>
</div>


{% endblock %}

jp_app/templates/jp_app/product/product-detail.html
{% extends 'jp_app/base.html' %}

{% block title %}Product{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<br>
<div class="p-3 mb-2 bg-info text-white">PODROBNOSTI PRODUKTU</div>

<div class="jumbotron">
    <h1 class="display-4">{{ product.name }}</h1>
    <p class="lead">Typ pruduktu: <b>{{ product.product_type }}</b></p>
    <p class="lead">Obsah produktu: <b><br>{% for item in product.items.all %}{{ item.name }} - {{ item.costs }} Kč {% if item.note %}({{item.note}}){% endif %}<br/>{% endfor %}</b></p>
    <p class="lead">Výrobní náklady: <b>{{ product.production_costs }} Kč</b></p>
    <p class="lead">Prodané množství: <b>{{ product.sold }} ks</b></p>
    <p class="lead">J&P CANDLES: <b>{% if post.jp_candles %}Ano{% endif %}{% if not post.jp_candles %}Ne{% endif %}</b></p>
    <p class="lead">Produkt přidán: <b>{{ product.created|date:'d.m.Y' }}</b></p>
    <hr class="my-4">
    <p class="lead">Postup přípravy produktu: {{ product.procedure|safe }}</p>
    <hr class="my-4">
    <p>Poznámky:<br>{{ product.note }}</p>
    <p class="lead">
        <a class="btn btn-info btn-lg" href="{% url 'jp_app:product_update' product.pk %}" role="button">Editovat</a>
        <a class="btn btn-danger btn-lg" href="{% url 'jp_app:product_delete' product.pk %}" role="button">Smazat</a>
    </p>
</div>
{% endblock %}

jp_app/templates/jp_app/product/product.html
<!DOCTYPE html>
<html>
<style>
    span.small {
  font-size: smaller;
}
    table,
    th,
    td {
        border: 1px solid black;
    }
</style>

<body>

{% extends 'jp_app/base.html' %}

{% block title %}Product{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<br>

<a href="{% url 'jp_app:render_pdf' %}" class="btn btn-danger btn-sm">PDF</a>

<span class="small">

<div class="p-3 mb-2 bg-dark text-white">PRODUKTY</div>

<div class="p-2 mb-2 bg-info text-black"><strong>Seznam produktů</strong></div>
<p>Celkový počet položek: {{ object_list.count }}</p>
<div class="table-responsive">
<table class="table table-striped table-sm">
    <thead class="table-info">
        <tr>
            <th scope="col">Název produktu</th>
            <th scope="col">Typ produktu</th>
            <th scope="col">Obsah produktu</th>
            <th scope="col">Výrobní náklady</th>
            <th scope="col">Prodáno ks (množství)</th>
            <th scope="col">J&P CANDLES</th>
            <th scope="col">Poznámky</th>
            <th scope="col">Přidáno</th>
            <th scope="col">Editace</th>
            <th scope="col">Smazání</th>
        </tr>
    </thead>
    <tbody>
        
        {% for post in object_list %}
 
            <tr>
                <th scope="row"><a href="{% url 'jp_app:product-detail' post.pk %}">{{ post.name }}</a></th>
                <td>{{ post.product_type }}</td>
                <td>{% for item in post.items.all %}{{ item.name }}<br/>{% endfor %}</td>
                <td>{{ post.production_costs }} Kč</td>
                <td>{{ post.sold }}</td>
                <td>{% if post.jp_candles %}Ano{% endif %}{% if not post.jp_candles %}Ne{% endif %}</td>
                <td>{{ post.note }}</td>
                <td>{{ post.created|date:'d.m.Y' }}</td>
                <td><a href="{% url 'jp_app:product_update' post.pk %}" class="btn btn-info btn-sm">Editovat</a></td>
                <td><a href="{% url 'jp_app:product_delete' post.pk %}" class="btn btn-danger btn-sm">Smazat</a></td>
            </tr>
  
        {% endfor %}
    </tbody>
</table>
</div>
</span>


<!-- slouží k zobrazení stránkování - možnost přecházení mezi jednotlivými stranami seznamu rozděleného do více listů -->
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}




{% endblock %}

jp_app/templates/jp_app/product/product_add.html
<!DOCTYPE html>
<html>
<style>
    span.small {
  font-size: smaller;
}
</style>

<body>
    
{% extends 'jp_app/base.html' %}

{% block title %}Product{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<span class="small">

    <br>
<div class="p-3 mb-2 bg-info text-white">PRODUKTY</div>

<hr>

<div class="col">
    <div class="card text-white bg-success">
        <div class="card-body">
            <h5 class="card-title">Tvorba produktu</h5>
            <p class="card-text">
                <form method="POST">
                    {% csrf_token %}
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <a class="btn btn-outline-light btn-sm" href="/item/" role="button">Přidat ITEM (součást produktu)</a>
                    </div>
                    {{ form.media }}
                    {{ form.as_p }}
                    <button class="btn btn-dark">Přidat produkt</button>
                </form>
            </p>
        </div>
    </div>
</div>


</span>

{% endblock %}

jp_app/templates/jp_app/product/product_delete.html
{% extends 'jp_app/base.html' %}

{% block title %}Product{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<br>
<div class="p-3 mb-2 bg-danger text-white">SMAZÁNÍ PRODUKTU</div>

<hr>
<p><b>Nápad:</b> {{ idea.name }}</p>
<p><b>Typ nápadu:</b> {{ idea.product_type }}</p>
<p><b>Nápad vložen:</b> {{ idea.created }}</p><br><br>
<div class="form-row align-items-center">
    <div class="col-auto">
        <form method="POST">
            {% csrf_token %}
            <strong>Opravdu chcete smazat tento nápad?!</strong><br>
            <button class="btn btn-danger">Smazat</button>
        </form>
    </div>
</div>


{% endblock %}

jp_app/templates/jp_app/product/product_update.html
{% extends 'jp_app/base.html' %}

{% block title %}Product{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<br>
<div class="p-3 mb-2 bg-info text-white">PRODUKTY</div>

<hr>
<h2>Editace nápadu</h2>
<div class="form-row align-items-center">
    <div class="col-auto">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success">Upravit</button>
        </form>
    </div>
</div>


{% endblock %}