jp/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", v.register, name="register"),
    path("", include("jp_app.urls")),
    path("", include("to_do_list.urls")),
    path('', include("django.contrib.auth.urls")),
]

jp_app/urls.py
from django.urls import path

from . import views
from .views import IdeaView, IdeaDetailView, CreateIdea, UpdateIdea, DeleteIdea
from .views import ProductView, ProductDetailView, CreateProduct, UpdateProduct, DeleteProduct


app_name = 'jp_app'

urlpatterns = [
    path("", views.home, name="home"),
    path("<int:id>", views.index, name="index"),
    
    path("list", views.list, name="list"),
    path("create/", views.create, name="create"),
    
    path("product/", ProductView.as_view(), name="product"),
    path("product/<int:pk>", ProductDetailView.as_view(), name="product-detail"),
    path("product_update/<int:pk>", UpdateProduct.as_view(), name="product_update"),
    path("product_delete/<int:pk>", DeleteProduct.as_view(), name="product_delete"),
    path("product_add/", CreateProduct.as_view(), name="product_add"),
    
    path("item/", views.item, name="item"),
    path("item_update/<int:id>", views.item_update, name="item_update"),

    path("material/", views.material, name="material"),
    path("list_material/", views.list_material, name="list_material"),
    
    path("material_chart/", views.material_chart, name="material_chart"),
    path("statistic/", views.statistic, name="statistic"),
    path("stat_chart/", views.stat_chart, name="stat_chart"),
    
    path("google/", views.google, name="google"),
    
    path("render_pdf/",
         views.render_pdf, name="render_pdf"),
    
    path("idea/", IdeaView.as_view(), name="idea"),
    path("idea/<int:pk>", IdeaDetailView.as_view(), name="idea-detail"),
    path("idea_update/<int:pk>", UpdateIdea.as_view(), name="idea_update"),
    path("idea_delete/<int:pk>", DeleteIdea.as_view(), name="idea_delete"),
    path("idea_add/", CreateIdea.as_view(), name="idea_add"),
    
    # path('jp_candles/', include("jp_candles_app.urls"))
]

jp_app/views.py
from django import forms
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, FileResponse
from django.db.models import Sum, Count
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from collections import Counter

from .models import ProductType, Product, Item, SaleType, Sale, Transaction
from .models import MaterialType, Material, Storage, Removal
from .models import Idea

from .forms import ProductTypeForm, ProductForm, ItemForm, SaleTypeForm, SaleForm, TransactionForm, SearchForm
from .forms import MaterialTypeForm, MaterialForm, StorageForm, RemovalForm
from .forms import IdeaForm

from .filters import TransactionFilter

from .utils import (
    get_sales_channel_from_id,
    get_product_from_id, 
    get_chart_price,
    get_json,
)
    
import datetime
import pandas as pd
import json

### google drive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
import os

### pdf creator
import csv
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

from django.template.loader import render_to_string
from io import BytesIO
from xhtml2pdf import pisa


###   PRODEJ   ###



### zobrazí seznam všech produktů, i když zadám konkrétní "id"
def index(response, id):
    p = Product.objects.get(id=id)
    return render(response, "jp_app/list.html", {})

### zobrazí domovskou stránku (aktuálně bez obsahu)
def home(response):
    return render(response, "jp_app/home.html", {})


class ProductView(ListView):
    model = Product
    template_name = 'jp_app/product/product.html'
    ordering = ['-created']  # seřadí seznam produktů sestupně dle "data vložení"
    paginate_by = 15 ### pokud bude mít seznam více než  15 položek, rozdělí se v teplate na více stránek
    
    ### fce "get_context_data" umožňuje upravovat a přidávat pole/hodnoty v následně zobrazené template u class Views (v tomto případě ListView)
    ### v tomto případě fce spočítá celkové výrobní náklady z jednotlivých položek "items" obsažených/přiřazených danému produktu
    def get_context_data(self, **kwargs):
        ### "context" předdefinovaný (neměnit)
        context = super(ProductView, self).get_context_data(**kwargs)
        ### prochází postupně všechny produkty
        for p in Product.objects.all(): 
            i_sum=0
            ### prochází a postupně ukládá ceny ("costs") všech "items" obsažených v daném produktu
            for i in p.items.values('costs'):
                i_sum += i['costs']
            ### uloží do pole "production_costs" daného produktu celkovou částku za všechny "items" a tím vypočítá výrobní náklady daného produktu
            p.production_costs = i_sum
            p.save()
        ### "context" umožní zobrazení nově upraveného pole "production_costs" v template 'jp_app/product/product.html'
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'jp_app/product/product-detail.html'


### automaticky (pomocí CreateView) načte formulář sloužící k vložení produktů
class CreateProduct(SuccessMessageMixin, CreateView):
    ### "SuccessMessageMixin" slouží k tomu, aby se po vložení produktu a přesměrování na seznam produktů (k tomu slouží atribut "success_url") mohlo zobrazit potvrzení uložení
    model = Product  # models.py
    form_class = ProductForm  # forms.py
    # pokud kvůli bootstrap mám "template_name", musím zakomentovat "fields"
    template_name = 'jp_app/product/product_add.html'
    # template_name = 'jp_app/idea_add.html'
    # fields = '__all__'
    success_url = reverse_lazy('jp_app:product') ### po uložení produktu přesměruje na stránku se seznamem produktů
    success_message = "Produkt %(name)s byl úspěšně uložen" ### po vložení zobrazí upozornění
    

class UpdateProduct(UpdateView):
    model = Product
    form_class = ProductForm  # forms.py
    # pokud kvůli bootstrap mám "template_name", musím zakomentovat "fields"
    template_name = 'jp_app/product/product_update.html'
    # fields = '__all__'


class DeleteProduct(DeleteView):
    model = Product
    template_name = 'jp_app/product/product_delete.html'
    # 'reverse_lazy' slouží k určení stránky, na kterou po smazání nápadu bude přesměrováno
    success_url = reverse_lazy('jp_app:product')


### vytvoří a zobrazí seznam "items", tzn. jednotlivých položek, ze kterých se skládají produkty
def item(response):
    i = Item.objects.all()
    i_count = i.count()  ### fce počítá součet vložené typy produktů
    form_i = ItemForm()
    
    if response.method == "POST":
        if "save_i" in response.POST: 
            form_i = ItemForm(response.POST)
            if form_i.is_valid():
                form_i.save()
        if response.POST.get("delete_i"):
            # převede QueryDict na dictionary "id" položky, kterou chceme smazat
            x = response.POST.dict()['delete_i']
            # vyhledá odpovídající transakci (dle id=x)
            z = Item.objects.get(id=x)
            z.delete()  # vymaže danou položku naskladnění
            messages.success(response, ('Item byla úspěšně vymazán'))
    
    
    dict = {
        "i": i,
        "i_count": i_count,
        "form_i": form_i,
      }

    return render(response, "jp_app/product/item.html", dict)


### umožní editovat objekt "item"
def item_update(response, id):
    item = Item.objects.get(id=id)
    form = ItemForm(response.POST or None,
                    instance=item)
    if form.is_valid():
        form.save()
        messages.success(response, ('Item byla úspěšně změněna'))
        return redirect("/item")
    
    dict = {
        "form": form,
        "item": item,
    }
    
    return render(response, "jp_app/product/item_update.html", dict)



### zobrazí všechny položky kategorie prodej ###
def list(response):
    pt = ProductType.objects.all()
    p = Product.objects.all()
    st = SaleType.objects.all()
    s = Sale.objects.all()
    t = Transaction.objects.all()

    ### slouží k vymazání dané transakce ###
    if response.method == "POST":
        ### aktivace tlačítkem "delete" u příslušné transakce
        if response.POST.get("delete_t"):
            # převede QueryDict na dictionary "id" položky, kterou chceme smazat
            x = response.POST.dict()['delete_t']
            # vyhledá odpovídající transakci (dle id=x)
            z = Transaction.objects.get(id=x)
            z.delete()  # vymaže danou položku naskladnění
            messages.success(response, ('Transakce byla úspěšně vymazána'))
    
    ### další část kód slouží k výpočtu tržeb po jednotlivých dnech ###
    q = Transaction.objects.values('day_of_sale').distinct() ### uloží unikátní dny, ve kterých se uskutečnila transakce (class Transaction)
    #print(q)
    tt = []
    temp1 = 0
    total = 0
    for date in q: ### prochází postupně všechny dny, kdy se uskutečnila transakce
        t1 = Transaction.objects.filter(day_of_sale=date["day_of_sale"]) ### uloží konkrétní den dané iterace cyklu "for"
        #print(t1)
        #print(len(t1))
        temp = 0
        lst = []
        for x in range(len(t1)): ### prochází postupně všechny transakce daného dne
            #print(x)
            temp += (t1[x]).total_price  ### uloží utrženou částku za danou transakci
            
        ### We can use (*) operator to get all the values of the dictionary in a list
        temp_value = [*(q[temp1]).values()][0] ### uloží hodnotu data aktuální iterace (* a fce values slouží k očištění daného data, aby nebylo zabaleno v listu a dalo se dále uložit)
        lst.extend([temp_value, temp])  # přidá do dočasného listu datum z temp_value spolu s utrženou částkou v daném dni (fce"extend" je alternativou k "append" a slouží k vložení více hodnot do listu najdednou)
        #print(lst)
        tt.append(lst) ### vloží hodnoty z dočasného listu "lst" do finálního souhrnného listu "tt", který obsahuje všechny potřebného hodnoty pro výpis tržeb
        total += temp ### počítá celkovou utrženou částku za všechny transakce
        temp1 += 1
    #print(tt)


    ### vypočte, kolik bylo prodáno ks jednotlivých výrobků (z uskutečněných transakcí) ###
    id_p = Product.objects.values('id')
    ### prochází jednotlivé výrobky dle "id"
    for product in id_p:
        # print("id_p:", id_p)
        # print("product['id']:", product['id'])
        ### z trasakcí seskupených dle "id" prodaného výrobku vypočte celkový počet prodaných ks daného výrobku
        y = Transaction.objects.filter(product__id=product['id']).values(
            'product').annotate(sum=Sum('quantity_of_product')).values('sum')
        ### "z1" je list_comprehension, jehož výsledkem je ale list, proto se zatám nepoužívá a místo toho je níže "for z in y", které z QuerySetu vyndá počet prodaných výrobků pro další použití
        # z1 = ([z['sum'] for z in y])
        # print("z1:",z1)
        for z in y:
            ### najde produkt, který je aktuálně součástí daného cyklu "for product in id_p"
            pr1 = Product.objects.get(id=product['id'])
            ### k danému atributu "sold" daného produktu přiřadí počet prodaných ks a uloží ho
            pr1.sold = z['sum']
            pr1.save()

    print(t.values('day_of_sale'))
    
    ### tato část slouží k filtrování transakcí ###
    myFilter = TransactionFilter(response.GET, queryset=t) 
    t = myFilter.qs
    #print(t)

    ### fce počítá součet vložené typy produktů ###
    pt_count = pt.count()


    
    dict = {
        "pt": pt,
        "p": p,
        "st": st,
        "s": s,
        "t": t,
        "q": q,
        "myFilter": myFilter,
        "pt_count": pt_count,
        "tt": tt,  ### obsahuje všechny potřebného hodnoty pro výpis tržeb
        "total": total,  ### celková utržená částka za všechny transakce
         }

jp_app/templates/jp_app/base copy.html
<!doctype html>
<html>

<head>
    <style type="text/css">
        .sidenav {
            height: 100%;
            width: 250px;
            float:left;
            z-index: 1;
            border-right: 30px solid white;
            top: 0;
            left: 0;
            background-color: rgba(0, 0, 0, 0.74);
            overflow-x: :hidden;
            padding-top: 20px;
        }

        .sidenav a {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 25px;
            color: whitesmoke;
            display: block;
        }

        .sidenav a:hover {
            color: #f1f1f1;
        }

        .main {
            margin-left: 160px;
            padding: 0px 10px;
        }
    </style>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   
    <title>{% block title %}{% endblock %}</title>
    
    
</head>

<body>
    <div class="sidenav">
        <a href="/">Domů</a>
        <a href="/list">Přehled prodej</a>
        <a href="/list_material">Přehled sklad</a>
        <a href="/idea">Přehled nápady</a>
        <a href="/transaction_chart">Grafy prodej</a>
        <a href="/statistic">Statistiky prodeje</a>
        <a href="/create">Editace prodej</a>
        <a href="/material">Editace sklad</a>
        <a href="/idea_add">Editace nápady</a>
    </div>

    <div id="content", name="content", class="main">
        <div class="row justify-content-center">
            <div class="col-8">
                <h1 class="mt-2">{% load static %}
                <img src="{% static 'jp_app/J-P web special.png' %}" alt="My image"></h1>
                <hr class="mt-0 mb-4">
                {% if user.is_authenticated or request.path == "/login/" %}
                    {% block content %}
                    {% endblock %}
                {% else %}
                    <p>Login <a href="/login">Here</a></p>
                {% endif %}
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    
</body>
</html>

jp_app/templates/jp_app/base.html
<!doctype html>
<html>
{% load static %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    
    <!-- Date Picker (umožní v Bottstrap formulářové okno s kalendářem) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" charset="UTF-8"></script>

  
    <title>{% block title %}{% endblock %}</title>
    
    
</head>

<body>

    <!-- umožní, že se rozbalovací nabídka v navbar (menu) sama rozbalí, pokud na ni najedu myší -->
    <style type="text/css">
        .dropdown:hover>.dropdown-menu {
            display: block;
        }
    </style>


    <!-- navigační menu (bootstrap) -->

    <nav class="navbar navbar-expand-md sticky-top navbar-dark bg-dark">
        <div class="container-fluid">
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <!-- logo J&P Candles -->
            <a class="navbar-brand" href="/">
                <img src="{% static 'jp_app/J&P logo bílé.png' %}" width="70" height="70" alt="My image">
            </a>
            
            <!-- obsah -->
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/list">Prodej</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/product">Produkty</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/list_material">Sklad</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/idea">Nápady</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/google">Google</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/to_do_list">ToDoList</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Editace
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="/create">Editace prodej</a></li>
                            <li><a class="dropdown-item" href="/product_add">Přidání produktu</a></li>
                            <li><a class="dropdown-item" href="/item">Items</a></li>
                            <li><a class="dropdown-item" href="/material">Editace sklad</a></li>
                            <li><a class="dropdown-item" href="/idea_add">Editace nápady</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Statistiky
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="/material_chart">Skladové zásoby (Chart.js)</a></li>
                            <li><a class="dropdown-item" href="/statistic">Filtrované statistiky s grafem (Pandas)</a></li>
                            <li><a class="dropdown-item" href="/stat_chart">Statistiky a grafy (Chart.js)</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- slouží k zobrazování upozornění po vykonání nějaké funkce (např. uložení či vymazání položky) -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {% comment %} další kód "svg" obsahuje ikonu "i" jako informace {% endcomment %}
                <b><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16"> 
  <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
  <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
</svg> {{ message }}</b>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>            
        {% endfor %}
    {% endif %}

    <div id="content", name="content", class="main">
        <div class="row justify-content-center">
            <div class="col-8">
                <!-- <h1 class="mt-2">{% load static %}
                <img src="{% static 'jp_app/J-P web special.png' %}" alt="My image" class="img-fluid"></h1> -->
                <!-- <hr class="mt-0 mb-4"> -->
                {% if user.is_authenticated or request.path == "/login/" %}
                    {% block content %}
                    {% endblock %}
                {% else %}
                    <p>Login <a href="/login">Here</a></p>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    
    
    <!-- další kód slouží k pokročilejšímu zobrazování tabulek pomocí jQuery (dataTables)  -->

    <script src="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.filter.html.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/plug-ins/1.10.19/sorting/datetime-moment.js"></script>

    <script type="text/javascript">
        console.log("js ready");
        $(document).ready(function () {
            console.log("Jquery ready");
            $.fn.dataTable.moment( 'YYYY,MM,DD' );
            $('#myTable').dataTable({
                language: {
                    url: 'http://cdn.datatables.net/plug-ins/1.12.1/i18n/cs.json',
                }                    

            });
        });
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

    <script type="text/javascript">
        console.log("js ready");
        $(document).ready(function () {
            console.log("Jquery ready");
            $.fn.dataTable.moment( 'YYYY,MM,DD' );
            $('#myTable1').dataTable({
                language: {
                    url: 'http://cdn.datatables.net/plug-ins/1.12.1/i18n/cs.json',
                }

            });
        });
    </script>

    <script type="text/javascript">
        console.log("js ready");
        $(document).ready(function () {
            console.log("Jquery ready");
            $.fn.dataTable.moment( 'YYYY,MM,DD' );
            $('#myTable2').dataTable({
                language: {
                    url: 'http://cdn.datatables.net/plug-ins/1.12.1/i18n/cs.json',
                }

            });
        });
    </script>
    
</body>
</html>

jp_app/templates/jp_app/google.html
<!DOCTYPE html>
<html>
<style>
    table,
    th,
    td {
        border: 1px solid black;
    }
</style>

<body>

{% extends 'jp_app/base.html' %}

{% block title %}Google{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<br>

<div class="p-3 mb-2 bg-dark text-white">GOOGLE</div>



{% endblock %}

jp_app/templates/jp_app/idea-detail.html
{% extends 'jp_app/base.html' %}

{% block title %}Idea List{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<div class="p-3 mb-2 bg-info text-white">PODROBNOSTI NÁPADU</div>

<div class="jumbotron">
    <h1 class="display-4">{{ idea.name }}</h1>
    <p class="lead">Typ pruduktu: <b>{{ idea.product_type }}</b></p>
    <p class="lead">Výrobní náklady: <b>{{ idea.production_costs }}</b></p>
    <p class="lead">Prodejní cena: <b>{{ idea.selling_price }}</b></p>
    <p class="lead">Předpoklad uvedení na trh: <b>{{ idea.introduction_day }}</b></p>
    <p class="lead">Status: <b>{{ idea.status }}</b></p>
    {% load static %}
    <img class="card-img-right" src="{% static 'jp_app/DSC00293_2.jpg' %}" alt="Card image cap">
    <hr class="my-4">
    <p><b>Poznámky:</b><br>{{ idea.note }}</p>
    <p class="lead">
        <a class="btn btn-info btn-lg" href="{% url 'jp_app:idea_update' idea.pk %}" role="button">Editovat</a>
        <a class="btn btn-danger btn-lg" href="{% url 'jp_app:idea_delete' idea.pk %}" role="button">Smazat</a>
    </p>
</div>
{% endblock %}

jp_app/templates/jp_app/idea.html
<!DOCTYPE html>
<html>
<style>
    table,
    th,
    td {
        border: 1px solid black;
    }
</style>

<body>

{% extends 'jp_app/base.html' %}

{% block title %}Idea{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<br>

<div class="p-3 mb-2 bg-dark text-white">NÁPADY</div>

<div class="p-2 mb-2 bg-info text-black"><strong>Seznam nápadů</strong></div>
<p>Celkový počet položek: {{ object_list.count }}</p>
<div class="table-responsive">
<table class="table table-striped table-sm">
    <thead class="table-info">
        <tr>
            <th scope="col">Název produktu</th>
            <th scope="col">Typ produktu</th>
            <th scope="col">Výrobní náklady</th>
            <th scope="col">Prodejní cena</th>
            <th scope="col">Předpoklad uvedení na trh</th>
            <th scope="col">Stav</th>
            <th scope="col">Editace</th>
            <th scope="col">Smazání</th>
        </tr>
    </thead>
    <tbody>
        {% for post in object_list %}
            <tr>
                <th scope="row"><a href="{% url 'jp_app:idea-detail' post.pk %}">{{ post.name }}</a></th>
                <td>{{ post.product_type }}</td>
                <td>{{ post.production_costs }}</td>
                <td>{{ post.selling_price }}</td>
                <td>{{ post.introduction_day|date:'d.m.Y' }}</td>
                <td>{{ post.status }}</td>
                <td><a href="{% url 'jp_app:idea_update' post.pk %}" class="btn btn-info btn-sm">Editovat</a></td>
                <td><a href="{% url 'jp_app:idea_delete' post.pk %}" class="btn btn-danger btn-sm">Smazat</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% endblock %}